# Generated by Django 6.0 on 2025-12-05 01:41

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[core.models.validate_nigerian_phone])),
                ('driver_id', models.CharField(blank=True, max_length=15, unique=True)),
                ('license_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[core.models.validate_nigerian_phone])),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('school', models.CharField(default='Federal University of Technology Minna', max_length=100)),
                ('is_verified_student', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('referral_count', models.IntegerField(default=0)),
                ('free_trips', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
