# Generated by Django 6.0 on 2025-12-05 01:48

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[core.models.validate_nigerian_phone])),
                ('full_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(max_length=20, unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('price_student', models.DecimalField(decimal_places=0, default=4000, max_digits=10)),
                ('price_regular', models.DecimalField(decimal_places=0, default=18000, max_digits=10)),
                ('bus_capacity', models.IntegerField(default=14)),
                ('passengers_boarded', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('used_free_trip', models.BooleanField(default=False)),
                ('is_boarded', models.BooleanField(default=False)),
                ('booked_by', models.CharField(choices=[('student', 'Student'), ('regular', 'Regular Passenger')], max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('regular_passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.regularpassenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip')),
            ],
        ),
    ]
